### ISSUE TITLE
cargo build failed on linux

### ISSUE THREAD

**Issue by didebughu** [google/vandalir#6]
my env:  clang_14,   souffle 2.3-177-g30df8ffa2,   gcc 8.5.0,   rust 1.67.1

error: linking with `cc` failed: exit status: 1
......
......
= note: /root/hjd/vandalir/target/release/deps/libsouffle_wrapper-da30d6751516898b.rlib(af0cf26678fdff10-lib.rs.o): In function `souffle::ReadFileCSV::getFileName(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)':
          lib.rs.cc:(.text._ZN7souffle11ReadFileCSV11getFileNameERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_St4lessIS7_ESaISt4pairIKS7_S7_EEE[_ZN7souffle11ReadFileCSV11getFileNameERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_St4lessIS7_ESaISt4pairIKS7_S7_EEE]+0xd7): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
          lib.rs.cc:(.text._ZN7souffle11ReadFileCSV11getFileNameERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_St4lessIS7_ESaISt4pairIKS7_S7_EEE[_ZN7souffle11ReadFileCSV11getFileNameERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_St4lessIS7_ESaISt4pairIKS7_S7_EEE]+0xdf): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

It looks like the problem is filesystem.
Should I update my gcc version?

**Comment by dmitryya** [comment]
Linux is my main dev environment, so this bug surprises me. I use `gcc (Debian 12.2.0-10) 12.2.0`. Try to update the gcc.

**Comment by didebughu** [comment]
Wow！
I succeeded after update gcc version to 11.
Seems like the problem is that gcc8 need add -lstdc++fs to link <filesystem>.
